spring:
  application:
    name: Customer

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap:
          servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: dev_user
    password: secret123

  jpa:
    hibernate:
      ddl-auto: none

app:
  kafka:
    payment-result-topic: "payment-result-topic"
    order-created-topic: "order-created-topic"
    order-cancelled-topic: "order-cancelled-topic"
    order-created-consumers: "order-created-consumers-group"
    order-cancelled-consumers: "order-cancelled-consumers-group"

server:
  port: 8082

security:
  jwt:
    secret-key: qJ1RzYk8s+XyL1uEZh/6v5Q9D/A7l2fM3nT4uVc8N0Y=
    expire-length-ms: 3600000
