spring:
  application:
    name: Order

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap:
          servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: dev_user
    password: secret123

  jpa:
    hibernate:
      ddl-auto: none

app:
  kafka:
    orders-topic: "order-events"