spring:
  application:
    name: Order

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap:
          servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: dev_user
    password: secret123

  jpa:
    hibernate:
      ddl-auto: none

app:
  kafka:
    payment-result-topic: "payment-result-topic"
    delivery-result-topic: "delivery-result-topic"
    order-created-topic: "order-created-topic"
    delivery-created-topic: "delivery-created-topic"
    customer-payment-result-group: "customer-payment-result-group"
    delivery-result-group: "delivery-result-group"

  outbox:
      totalShards: 4
      interval: 1

server:
  port: 8080