spring:
  application:
    name: Order

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap:
          servers: localhost:9092
    producer:
      retries: 0
      acks: 1
      properties:
        request.timeout.ms: 3000        # Wait max 3s for broker response
        delivery.timeout.ms: 5000       # Entire send operation max 5s
        max.block.ms: 2000
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: dev_user
    password: secret123

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/order_db
    user: dev_user
    password: secret123
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

app:
  kafka:
    payment-result-topic: "payment-result-topic"
    delivery-result-topic: "delivery-result-topic"
    order-created-topic: "order-created-topic"
    delivery-created-topic: "delivery-created-topic"
    customer-payment-result-group: "customer-payment-result-group"
    delivery-result-group: "delivery-result-group"

  outbox:
      totalShards: 4
      interval: 1
      timeout: 10

server:
  port: 8080