spring:
  application:
    name: Delivery

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: dev_user
    password: secret123

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap:
          servers: localhost:9092

app:
  kafka:
    delivery-created-topic: "delivery-created-topic"
    delivery-created-consumers: "delivery-created-group-id"
    delivery-result-topic: "delivery-result-topic"

server:
  port: 8081